# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hyperkey < Formula
  desc "Terminal-based keyboard practice app with adaptive learning"
  homepage "https://github.com/farseenmanekhan1232/hyperkey"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/farseenmanekhan1232/hyperkey/releases/download/v0.1.8/hyperkey_0.1.8_darwin_amd64.tar.gz"
      sha256 "8415aedb0929588dd6349be5cc19ebf57ba9f2f3146807746290dbda998802bc"

      def install
        bin.install "hyperkey"
      end
    end
    on_arm do
      url "https://github.com/farseenmanekhan1232/hyperkey/releases/download/v0.1.8/hyperkey_0.1.8_darwin_arm64.tar.gz"
      sha256 "d58085d49c6a53ed2839c2c33d231ddfb0372b8b7e74f172f1175d5c92a793f5"

      def install
        bin.install "hyperkey"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/farseenmanekhan1232/hyperkey/releases/download/v0.1.8/hyperkey_0.1.8_linux_amd64.tar.gz"
        sha256 "3567d433280dbdc21da5b7cbf8cd033024cb5c0f72f16c3aa08a614545fa3dc1"

        def install
          bin.install "hyperkey"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/farseenmanekhan1232/hyperkey/releases/download/v0.1.8/hyperkey_0.1.8_linux_arm64.tar.gz"
        sha256 "83bf7eb1698cb052eeae1204e2a85da9ffc70efceee604c6ecf619b78a4c6be6"

        def install
          bin.install "hyperkey"
        end
      end
    end
  end

  test do
    system "#{bin}/hyperkey", "--version"
  end
end
