# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tkeybr < Formula
  desc "Terminal-based keyboard practice app with adaptive learning"
  homepage "https://github.com/farseenmanekhan1232/tkeybr"
  version "0.3.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/farseenmanekhan1232/tkeybr/releases/download/v0.3.5/tkeybr_0.3.5_darwin_amd64.tar.gz"
      sha256 "3ad9ff68e6949a8f7c19b3a58c276986b55e3f7fdb0cdae5f712c5e11bcd8232"

      def install
        bin.install "tkeybr"
      end
    end
    on_arm do
      url "https://github.com/farseenmanekhan1232/tkeybr/releases/download/v0.3.5/tkeybr_0.3.5_darwin_arm64.tar.gz"
      sha256 "55300fba79a66153e3164d024badc7437b02cb79be9d1163229c5d0bfc045a25"

      def install
        bin.install "tkeybr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/farseenmanekhan1232/tkeybr/releases/download/v0.3.5/tkeybr_0.3.5_linux_amd64.tar.gz"
        sha256 "269c037ac41aabc25f4c8226cb4eb777a17ea1e195ae882a3c13c04afcf7809b"

        def install
          bin.install "tkeybr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/farseenmanekhan1232/tkeybr/releases/download/v0.3.5/tkeybr_0.3.5_linux_arm64.tar.gz"
        sha256 "310b034a36c7eabf3b5a7fedf109a030224095fc924ce0ebdcf1749a3acd2005"

        def install
          bin.install "tkeybr"
        end
      end
    end
  end

  test do
    system "#{bin}/tkeybr", "--version"
  end
end
